#define MAX_INPUT_LENGTH    50
#define MAX_OUTPUT_LENGTH   400

#include <string.h>
#include "FreeRTOS.h"
#include "FreeRTOS_CLI.h"
#include "projdefs.h"
#include "console.h"

static char * pcWelcomeMessage =
  "\r\n\r\n\r\nSTM32H7 SOM FreeRTOS CLI, www.emcraft.com\r\n"
  "Type help to view a list of available commands.\r\n";

/* The input and output buffers are declared static to keep them off the stack. */
static char pcOutputString[ MAX_OUTPUT_LENGTH ];
static char pcInputString[ MAX_INPUT_LENGTH ];

void vCommandConsoleTask( void *pvParameters )
{
	int8_t cRxedChar, cInputIndex = 0;
	BaseType_t xMoreDataToFollow;
	char * prompt = "CLI> ";

	/* Send a welcome message to the user knows they are connected. */
	console_puts((char *)pcWelcomeMessage);
	console_puts(prompt);
	for( ;; )
	{
		/* This implementation reads a single character at a time.  Wait in the
		Blocked state until a character is received. */
		cRxedChar = console_getc();

		if( cRxedChar == '\r' )
		{
			/* A newline character was received, so the input command string is
			complete and can be processed.  Transmit a line separator, just to
			make the output easier to read. */
			console_puts("\r\n");

			/* The command interpreter is called repeatedly until it returns
			pdFALSE.  See the "Implementing a command" documentation for an
			explanation of why this is. */
			do
			{
				/* Send the command string to the command interpreter.  Any
				output generated by the command interpreter will be placed in the
				pcOutputString buffer. */
				xMoreDataToFollow = FreeRTOS_CLIProcessCommand(
					pcInputString,		/* The command string.*/
					pcOutputString,		/* The output buffer. */
					MAX_OUTPUT_LENGTH	/* The size of the output buffer. */);

				/* Write the output generated by the command interpreter to the console. */
				if (strlen(pcOutputString) > 0) {
					console_puts((char *)pcOutputString);
					console_puts("\r\n");
				}
			} while( xMoreDataToFollow != pdFALSE );
			console_puts(prompt);

			/* All the strings generated by the input command have been sent.
			Processing of the command is complete.  Clear the input string ready
			to receive the next command. */
			cInputIndex = 0;
			memset( pcInputString, 0x00, MAX_INPUT_LENGTH );
		}
		else
		{
			console_putc(cRxedChar);
			/* The if() clause performs the processing after a newline character
			is received.  This else clause performs the processing if any other
			character is received. */
			if( cRxedChar == '\b' || cRxedChar == 127 )
			{
				/* Backspace was pressed.  Erase the last character in the input
				buffer - if there are any. */
				if( cInputIndex > 0 )
				{
					cInputIndex--;
					pcInputString[ cInputIndex ] = 0;
				}
			}
			else
			{
				/* A character was entered.  It was not a new line, backspace
				or carriage return, so it is accepted as part of the input and
				placed into the input buffer.  When a \n is entered the complete
				string will be passed to the command interpreter. */
				if( cInputIndex < MAX_INPUT_LENGTH )
				{
					pcInputString[ cInputIndex ] = cRxedChar;
					cInputIndex++;
				}
			}
		}
	}
}
