CONFIG_SYS_SPI_U_BOOT_OFFS=0x00000000
CONFIG_BOOTM_NETBSD=y
CONFIG_SYS_FLASH_SECT_SIZE=0x20000
CONFIG_BOOTM_VXWORKS=y
CONFIG_ENV_UBI_PART="system"
CONFIG_IS_MODULE(option)="config_enabled(CONFIG_VAL(option ##_MODULE))"
CONFIG_SYS_LOAD_ADDR=0xD0400000
CONFIG_SYS_HELP_CMD_WIDTH=10
CONFIG_BOOTM_RTEMS=y
CONFIG_SYS_CBSIZE=256
CONFIG_BOARD_LATE_INIT=y
CONFIG_REVISION_TAG=y
CONFIG_FB_ADDR=0xD0000000
CONFIG_ENV_SIZE="(0x4000)"
CONFIG_SPL_BUILD=y
CONFIG_SYS_MALLOC_LEN="(1 * 1024 * 1024)"
CONFIG_INITRD_TAG=y
CONFIG_SPLASH_SCREEN=y
CONFIG_BOOTM_PLAN9=y
CONFIG_IS_BUILTIN(option)="config_enabled(CONFIG_VAL(option))"
CONFIG_SPL_TEXT_BASE=$(CONFIG_SYS_FLASH_BASE)
CONFIG_VIDEO_BMP_RLE8=y
CONFIG_ENV_UBI_VOLUME_REDUND="env2"
CONFIG_BOOTM_LINUX=y
CONFIG_SYS_MAXARGS=16
CONFIG_EXTRA_ENV_SETTINGS=""kernel_addr_r=0xD00080000fdtfile=stm32h7_som.dtb0fdt_addr_r=0xD07000000scriptaddr=0xD08000000pxefile_addr_r=0xD08000000fdt_high=0xffffffffffffffff0initrd_high=0xffffffffffffffff0ramdisk_addr_r=0xD09000000bootcmd=run reliable_boot; if test x$upgrade_available = x1; then reset; fi0altbootcmd=run reliable_altboot0ubiboot=ubi read $loadaddr rtos$boot_num && bootm0reliable_boot= setenv boot_num 0; if test x$boot2_active != x1 -a x$boot1_valid = x1; then   setenv boot_num 1; fi; if test x$boot2_active  = x1 -a x$boot2_valid = x1; then   setenv boot_num 2; fi; if test x$boot_num != x0; then   echo "Booting Image #${boot_num}";   run ubiboot ||       echo ERROR: ubiboot($boot_num) failed; else   echo ERROR: Active image set is invalid; fi;0reliable_altboot= if test x$boot2_active != x1; then   setenv boot2_active 1;   setenv boot1_valid 0; else   setenv boot2_active 0;   setenv boot2_valid 0; fi; setenv upgrade_available 0; setenv bootcount 0; saveenv; reset;0" CONFIG_MTDPARTS_DEFAULT "0" BOOTENV"
CONFIG_BOARDDIR="board/emcraft/stm32h7-som"
CONFIG_SYS_UBOOT_START=0x240013FC
CONFIG_SPL_STACK="(0x20010000)"
CONFIG_BOOTCOMMAND="run distro_bootcmd"
CONFIG_ZLIB=y
CONFIG_LOADADDR=0xD0400000
CONFIG_PRAM=0
CONFIG_GZIP=y
CONFIG_DMAMEM_SIZE_ORDER=22
CONFIG_SYS_BAUDRATE_TABLE="{ 9600, 19200, 38400, 57600, 115200 }"
CONFIG_VAL(option)="config_val(option)"
CONFIG_BMP_24BPP=y
CONFIG_SPL_PAD_TO=0
CONFIG_SYS_INIT_SP_ADDR=0x20020000
CONFIG_CMDLINE_TAG=y
CONFIG_BMP_16BPP=y
CONFIG_SPLASH_SCREEN_ALIGN=y
CONFIG_SYS_BOOT_RAMDISK_HIGH=y
CONFIG_SYS_MEMTEST_END=0xD1f00000
CONFIG_BMP_32BPP=y
CONFIG_SYS_FLASH_BASE=0x08000000
CONFIG_SYS_HZ_CLOCK=1000000
CONFIG_SYS_MAX_FLASH_BANKS=y
CONFIG_SYS_PBSIZE="(CONFIG_SYS_CBSIZE + sizeof(CONFIG_SYS_PROMPT) + 16)"
CONFIG_ENV_UBI_VOLUME="env1"
CONFIG_SYS_REDUNDAND_ENVIRONMENT=y
CONFIG_SETUP_MEMORY_TAGS=y
CONFIG_SYS_MEMTEST_START=0xD0000000
CONFIG_STM32H7_FLASH=y
CONFIG_LMB=y
CONFIG_SYS_MAX_FLASH_SECT=y
CONFIG_IS_ENABLED(option)="(config_enabled(CONFIG_VAL(option)) || config_enabled(CONFIG_VAL(option ##_MODULE)))"
CONFIG_DWC_ETH_QOS_DESCRIPTORS=0xD03FFF80
CONFIG_DMAMEM_START=0xD0000000
